https://www.youtube.com/watch?v=r7QDUPb2dCM&list=PL_lsbAsL_o2CTlGHgMxNrKhzP97BaG9ZN&index=2&pp=iAQB

In [1]:
import torch
import math

In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.1022e-14, 4.5835e-41, 1.1022e-14, 4.5835e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
zeros = torch.zeros(2,3)
print(zeros)

ones = torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)

random2 = torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3)

random4 = torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2,2,3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.1137e-34, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 3.4455e-10, 4.5834e-41]]])
torch.Size([2, 2, 3])
tensor([[[1.0886e-34, 0.0000e+00, 1.1030e-34],
         [0.0000e+00, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 1.1137e-34],
         [0.0000e+00, 0.0000e+00, 1.1755e-38]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
some_constants = torch.tensor([[3.2342, 2.32423],[.1234, 5.234234]])
print(some_constants)

some_integers = torch.tensor((2,3,5,7,11,13,17,19))
print(some_integers)

more_integers = torch.tensor(((2,4,6), [3,6,9]))
print(more_integers)

tensor([[3.2342, 2.3242],
        [0.1234, 5.2342]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [8]:
a = torch.ones((2,3), dtype=torch.int16)
print(a)

b = torch.rand((2,3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


In [10]:
ones = torch.zeros(2,2) + 1
twos = torch.ones(2,2) * 2
threes = (torch.ones(2,2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [11]:
powers2 = twos ** torch.tensor([[1,2],[3,4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [12]:
a = torch.rand(2,3)
b = torch.rand(3,2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [13]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


In [14]:
a = torch.ones(4,3,2)

b = a*torch.rand(3,2) # 3rd and 2nd dims identical to a, dim 1 absent
print(b)

c = a*torch.rand(3,1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a*torch.rand(1,2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [15]:
a = torch.ones(4,3,2)

b = a*torch.rand(4,3) # dims must match last-to-first
print(b)

c = a*torch.rand(2,3) # both 3rd and 2nd dims different
print(c)

d = a*torch.rand((0,)) # can't broadcast with an empty tensor
print(d)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [25]:
a = torch.rand(2,4) * 2 -1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5,0.5))

# trignometric functions
angles = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSines and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise
print('\nBitwise XOR:')
b = torch.tensor([1,5,11])
c = torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

# comparisons
print('\nBroadcasted, element-wise equality comparisons:')
d = torch.tensor([[1.,2.],[3.,4.]])
e = torch.ones(1,2) # broadcasting
print(torch.eq(d,e))

# reductions
print('\nReduction ops:')
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d)) # product of all numbers
print(torch.unique(torch.tensor([1,2,1,2,1,2]))) # filter unique numbers

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.]) # x unit vector
v2 = torch.tensor([0., 1., 0.]) # y unit vector
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.], [0.,3.]]) # 3*I

print('\nVectors and Matrices')
print(torch.linalg.cross(v2, v1)) # negative of x unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)  # 3 * m1
print(torch.svd(m3)) # SVD

Common functions:
tensor([[0.8260, 0.9665, 0.5411, 0.5652],
        [0.5923, 0.4237, 0.4646, 0.3867]])
tensor([[1., 1., 1., -0.],
        [-0., -0., -0., -0.]])
tensor([[ 0.,  0.,  0., -1.],
        [-1., -1., -1., -1.]])
tensor([[ 0.5000,  0.5000,  0.5000, -0.5000],
        [-0.5000, -0.4237, -0.4646, -0.3867]])

Sines and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparisons:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors and Matrices
tensor([ 0.,  0., -1.])
tensor([[0.6961, 0.5406],
        [0.5028, 0.0389]])
tensor([[2.0883, 1.6218],
        [1.5083, 0.1166]])
torch.return_types.svd(
U=tensor([[-0.8876, -0.4605],
        [-0.4605,  0.8876]]),
S=tensor([2.9536, 0.7458]),
V=tensor([[-0.8628,  0.5056],
        [-0.5056, -0.8628]]))


In [26]:
a = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('\nb:')
print(b)
print(torch.sin_(b)) # in-place
print(b)


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [27]:
a = torch.ones(2,2)
b = torch.rand(2,2)

print('Before:')
print(a)
print(b)
print('\nAfter addtion:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1795, 0.1413],
        [0.7666, 0.1920]])

After addtion:
tensor([[1.1795, 1.1413],
        [1.7666, 1.1920]])
tensor([[1.1795, 1.1413],
        [1.7666, 1.1920]])
tensor([[0.1795, 0.1413],
        [0.7666, 0.1920]])

After multiplying
tensor([[0.0322, 0.0200],
        [0.5877, 0.0369]])
tensor([[0.0322, 0.0200],
        [0.5877, 0.0369]])


In [28]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)

assert c is d
assert id(c), old_id

torch.rand(2,2,out=c)
print(c)
assert id(c), old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.7622, 0.4266],
        [0.8982, 0.6873]])
tensor([[0.0425, 0.0313],
        [0.5074, 0.7209]])


In [29]:
a = torch.ones(2,2)
b = a
a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [30]:
a = torch.ones(2,2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [31]:
a = torch.rand(2,2, requires_grad=True)
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.6635, 0.1084],
        [0.1523, 0.8454]], requires_grad=True)
tensor([[0.6635, 0.1084],
        [0.1523, 0.8454]], grad_fn=<CloneBackward0>)
tensor([[0.6635, 0.1084],
        [0.1523, 0.8454]])
tensor([[0.6635, 0.1084],
        [0.1523, 0.8454]], requires_grad=True)


In [36]:
if torch.cuda.is_available():
    print('We have', torch.cuda.device_count(), 'GPU(s)!')
else:
    print('Sorry, CPU only.')

We have 1 GPU(s)!


In [34]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2,2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [38]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2,2, device=my_device)
print(x)

Device: cuda


RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [39]:
y = torch.rand(2,2)
y = y.to(my_device)

RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [40]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [41]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.7302]]]]])


In [42]:
a = torch.rand(1,20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2,2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.5719, 0.4672, 0.1316, 0.2789, 0.7389, 0.3947, 0.7705, 0.0227, 0.2371,
         0.5902, 0.5563, 0.1966, 0.2077, 0.8869, 0.7977, 0.4532, 0.1746, 0.2414,
         0.2355, 0.9062]])
torch.Size([20])
tensor([0.5719, 0.4672, 0.1316, 0.2789, 0.7389, 0.3947, 0.7705, 0.0227, 0.2371,
        0.5902, 0.5563, 0.1966, 0.2077, 0.8869, 0.7977, 0.4532, 0.1746, 0.2414,
        0.2355, 0.9062])
torch.Size([2, 2])
torch.Size([2, 2])


In [43]:
a = torch.ones(4,3,2)
b = torch.rand(3)
c = b.unsqueeze(1)
print(c.shape)
print(a*c)

torch.Size([3, 1])
tensor([[[0.0906, 0.0906],
         [0.3839, 0.3839],
         [0.4696, 0.4696]],

        [[0.0906, 0.0906],
         [0.3839, 0.3839],
         [0.4696, 0.4696]],

        [[0.0906, 0.0906],
         [0.3839, 0.3839],
         [0.4696, 0.4696]],

        [[0.0906, 0.0906],
         [0.3839, 0.3839],
         [0.4696, 0.4696]]])


In [44]:
batch_me = torch.rand(3,226,226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [45]:
output3d = torch.rand(6,20,20)
print(output3d.shape)

input1d = output3d.reshape(6*20*20)
print(input1d.shape)

print(torch.reshape(output3d, (6*20*20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [46]:
import numpy as np

nparray = np.ones((2,3))
print(nparray)

pytorch_tensor = torch.from_numpy(nparray)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [47]:
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5413, 0.7529, 0.0877],
        [0.7201, 0.0580, 0.2624]])
[[0.5413369  0.75290173 0.08767194]
 [0.72013265 0.05796134 0.26237112]]


In [48]:
nparray[1,1] = 23
print(pytorch_tensor)

pytorch_rand[1,1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.5413369   0.75290173  0.08767194]
 [ 0.72013265 17.          0.26237112]]
